config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/demichie/elicipy2:
      branch: main
      repo: https://github.com/demichie/elicipy2
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/demichie/elicipy2 git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-myrtle-oyster.sh
        container: qc.acc_crappy-thistle-liger
  QC.Doc:
    repos:
      github.com/demichie/elicipy2 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-cerise-barnacle.sh
        container: qc.doc_cozy-corn-chamois
      github.com/demichie/elicipy2 git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-platinum-shrimp.sh
        container: qc.doc_whiny-gold-leopard
      github.com/demichie/elicipy2 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-khaki-badger.sh
        container: qc.doc_ugly-pumpkin-gopher
  QC.Lic:
    repos:
      github.com/demichie/elicipy2 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-linen-wasp.sh
        container: qc.lic_cloudy-azure-armadillo
  QC.Met:
    repos:
      github.com/demichie/elicipy2 cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-cerulean-crab.sh
        container: qc.met_stuffy-maroon-bonobo
  QC.Sec:
    repos:
      github.com/demichie/elicipy2 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-beige-weasel.sh
        container: qc.sec_beady-rust-baboon
  QC.Sty:
    repos:
      github.com/demichie/elicipy2 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-lime-snail.sh
        container: qc.sty_wheezy-copper-ragdoll
  QC.Uni:
    repos:
      github.com/demichie/elicipy2 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-taupe-rabbit.sh
        container: qc.uni_whiny-white-alligator
  QC.Ver:
    repos:
      github.com/demichie/elicipy2 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-cardinal-angelfish.sh
        container: qc.ver_chummy-olive-tortoise
timeout: 5400
