config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/demichie/elicipy2:
      branch: main
      repo: https://github.com/demichie/elicipy2
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/demichie/elicipy2 git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-azure-swan.sh
        container: qc.acc_pasty-emerald-deer
  QC.Doc:
    repos:
      github.com/demichie/elicipy2 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-sapphire-toad.sh
        container: qc.doc_stuffy-goldenrod-ant
      github.com/demichie/elicipy2 git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-salmon-civet.sh
        container: qc.doc_clammy-ochre-saola
      github.com/demichie/elicipy2 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-blue-squirrel.sh
        container: qc.doc_pasty-peach-mist
  QC.Lic:
    repos:
      github.com/demichie/elicipy2 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-black-dachshund.sh
        container: qc.lic_geeky-denim-labradoodle
  QC.Met:
    repos:
      github.com/demichie/elicipy2 cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-mustard-guppy.sh
        container: qc.met_gimpy-asparagus-impala
  QC.Sec:
    repos:
      github.com/demichie/elicipy2 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-cornflower-frise.sh
        container: qc.sec_seedy-harlequin-dogfish
  QC.Sty:
    repos:
      github.com/demichie/elicipy2 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-burgundy-eel.sh
        container: qc.sty_squirrely-vermilion-maltese
  QC.Uni:
    repos:
      github.com/demichie/elicipy2 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.beady-saffron-fowl.sh
        container: qc.uni_dorky-cerise-fossa
  QC.Ver:
    repos:
      github.com/demichie/elicipy2 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-salmon-wolfhound.sh
        container: qc.ver_snoopy-asparagus-raccoon
timeout: 5400
