config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/demichie/elicipy2:
      branch: main
      repo: https://github.com/demichie/elicipy2
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/demichie/elicipy2 git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-burgundy-wombat.sh
        container: qc.acc_squeaky-harlequin-whippet
  QC.Doc:
    repos:
      github.com/demichie/elicipy2 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-purple-insect.sh
        container: qc.doc_woozy-asparagus-tortoise
      github.com/demichie/elicipy2 git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-razzmatazz-chamois.sh
        container: qc.doc_tacky-tangerine-quoll
      github.com/demichie/elicipy2 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-rust-angora.sh
        container: qc.doc_pokey-zucchini-weasel
  QC.Lic:
    repos:
      github.com/demichie/elicipy2 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-alizarin-abyssinian.sh
        container: qc.lic_stuffy-ecru-crocodile
  QC.Met:
    repos:
      github.com/demichie/elicipy2 cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-xanthic-mongoose.sh
        container: qc.met_gloppy-silver-capybara
  QC.Sec:
    repos:
      github.com/demichie/elicipy2 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-khaki-iguana.sh
        container: qc.sec_craggy-magenta-wrasse
  QC.Sty:
    repos:
      github.com/demichie/elicipy2 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-coral-snail.sh
        container: qc.sty_seedy-platinum-ragdoll
  QC.Uni:
    repos:
      github.com/demichie/elicipy2 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-auburn-fossa.sh
        container: qc.uni_silly-sepia-eleuth
  QC.Ver:
    repos:
      github.com/demichie/elicipy2 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-ruby-bird.sh
        container: qc.ver_tasty-rust-dalmatian
timeout: 5400
