config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/demichie/elicipy2:
      branch: main
      repo: https://github.com/demichie/elicipy2
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/demichie/elicipy2 git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-plum-dollar.sh
        container: qc.acc_sleepy-silver-seal
  QC.Doc:
    repos:
      github.com/demichie/elicipy2 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-wisteria-blue.sh
        container: qc.doc_scaly-tangerine-mammoth
      github.com/demichie/elicipy2 git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-heliotrope-vulture.sh
        container: qc.doc_scummy-orange-hound
      github.com/demichie/elicipy2 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-dandelion-bonobo.sh
        container: qc.doc_scaly-olivine-beetle
  QC.Lic:
    repos:
      github.com/demichie/elicipy2 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-apricot-woodpecker.sh
        container: qc.lic_homey-seashell-angora
  QC.Met:
    repos:
      github.com/demichie/elicipy2 cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-wheat-donkey.sh
        container: qc.met_snippy-brown-greyhound
  QC.Sec:
    repos:
      github.com/demichie/elicipy2 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-brown-iguana.sh
        container: qc.sec_tacky-apricot-tarsier
  QC.Sty:
    repos:
      github.com/demichie/elicipy2 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-aqua-salamander.sh
        container: qc.sty_snoopy-firebrick-hare
  QC.Uni:
    repos:
      github.com/demichie/elicipy2 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-periwinkle-sheepdog.sh
        container: qc.uni_chummy-ruby-oriole
  QC.Ver:
    repos:
      github.com/demichie/elicipy2 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-purple-woodpecker.sh
        container: qc.ver_stealthy-auburn-bear
timeout: 5400
