config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/demichie/elicipy2:
      branch: main
      repo: https://github.com/demichie/elicipy2
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/demichie/elicipy2 git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-emerald-rattlesnake.sh
        container: qc.acc_paltry-goldenrod-collie
  QC.Doc:
    repos:
      github.com/demichie/elicipy2 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-heliotrope-horse.sh
        container: qc.doc_craggy-teal-heron
      github.com/demichie/elicipy2 git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-amber-macaw.sh
        container: qc.doc_whiny-saffron-gharial
      github.com/demichie/elicipy2 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-brown-stoat.sh
        container: qc.doc_sunny-charcoal-audemer
  QC.Lic:
    repos:
      github.com/demichie/elicipy2 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-bistre-terrier.sh
        container: qc.lic_muzzy-cinnabar-mule
  QC.Met:
    repos:
      github.com/demichie/elicipy2 cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-magenta-newt.sh
        container: qc.met_dorky-cyan-moose
  QC.Sec:
    repos:
      github.com/demichie/elicipy2 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-teal-akbash.sh
        container: qc.sec_homely-bistre-chipmunk
  QC.Sty:
    repos:
      github.com/demichie/elicipy2 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-sepia-vole.sh
        container: qc.sty_hilly-aquamarine-ibis
  QC.Uni:
    repos:
      github.com/demichie/elicipy2 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-magnolia-dugong.sh
        container: qc.uni_gummy-xanthic-wombat
  QC.Ver:
    repos:
      github.com/demichie/elicipy2 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-indigo-chihuahua.sh
        container: qc.ver_leaky-flax-camel
timeout: 5400
